### ISSUE TITLE
not handle screen rotation

### ISSUE THREAD

**Issue by Dushistov** [yangh/sevensquare#14]
Thanks for your program.

I have android application that starts only landscape mode.

If I run `seven-square` and after that android-application (and before that android device was in portrait mode) I got this (screenshot of `seven-square`):
 
![garbage](https://user-images.githubusercontent.com/156697/28716899-40b9cbbc-73a8-11e7-9a8f-f6e5df1a41c4.png)

But if I run android-application and after run `seven-square` all looks great.

**Comment by yangh** [comment]
Hi Dush

You're welcome. Try to press F12 in seven-square to switch landscape and
potrit mode, to sew if it help

Best regard
Yang

**Comment by Dushistov** [comment]
@yangh No, pressing F12 not help, it rotates screen, but I still have the same garbage in the application screen: 
![grabage_rotate](https://user-images.githubusercontent.com/156697/28747979-6dc6a410-74b4-11e7-9500-bf0b3b88bc41.png)

**Comment by yangh** [comment]
Please try the latest code, may help with this.
