### ISSUE TITLE
Question: How to build patched screencap

### ISSUE THREAD

**Issue by mauron85** [yangh/sevensquare#15]
Firstly I want to thank you for this awesome tool. I used to use Vysor, but this is adequate free alternative.

Performance is OK, but I would liket to try minigzip with patched screencap. However I've no experience with building Android tools. I guess I need to download android SDK which is quite huge. Is there any faster way how to do it? Also what is mm tool?

Many Thanks

**Comment by yangh** [comment]
I don't think minizip/gzip will help much on the sluggish. we need a better solution, but that may require more action from the user's perspective, so I left it be so. Some commercial alternative has better performance, for example TC.
