### ISSUE TITLE
Asus ZC520KL Android 7.1.1 Repeat Connecting

### ISSUE THREAD

**Issue by godlatro** [yangh/sevensquare#17]
Asus ZC520KL Android 7.1.1 
Ubuntu Budgie 17.10 64bit 
NV 136
Intel Core i5-7500
Gnome 3.26.2
Repeat reConnecting always, but look works
When display is white in Settings menu SS work fine, but repeat connecting
If I open any displays it have many artifacts from center to bottom screen
If I open Camera image on screen very bad. It have so many artifacts and display distortion

My error console messages:
Adb exec error... 
1522262459975 ADB Wait for device 
1522262459984 ADB Found 
1522262459991 Compressed data transfer false 
1522262460173 Screencap on device options -q -s false false 
1522262460495 CAP FB in 322 ms 
1522262460619 Adb exec error... 
1522262460621 Device disconnected 
1522262460878 CAP FB in 351 ms 
1522262460905 Invalid FB data len: 3686395 require 3686400 
1522262463276 ADB Wait for device 
*** Error in `seven-square': free(): invalid size: 0x00007f9664529790 ***
Aborted (core dumped)

LG G2 4.4.2
Kernel 3.4.0
It work!
I see my screen, i can click on it, camera work too
But when I open something, screen update can wait for 3-10 seconds, and then update
BUT when I click - my phone get clicks immediately

Phillips V387 4.4.2 same problem as LG G2 - very slow screen update

**Comment by gabretana** [comment]
ADB tries to run screencap command with "-q" and "-s" options but from android 5 screencap only has 3 options -h for help, -p for save as png and -d for screen id and some custom roms have -j option to save image to png.

**Comment by yangh** [comment]
Transfer binary data (the screenshot of device) via ADB is not a good idea, but it can't be fixed in a simple way...

**Comment by ponty** [comment]
I had repeated disconnection. I fixed it in #26 and #27.

**Comment by yangh** [comment]
Fixed in latest commit 1333e50
