### ISSUE TITLE
Not installing -> Outdated version of Qt - 4 Required(perhaps) - Have 5

### ISSUE THREAD

**Issue by omar816** [yangh/sevensquare#20]
All the steps of the tutorial were going along quite well, but when it came time for..
...make 
I got the all the lines of output indicating something was happening, but the last few lines looked like this...
----------------------------------------------
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'seven-square' failed
make[1]: *** [seven-square] Error 1
make[1]: Leaving directory '/home/omar/sevensquare/build'
Makefile:11: recipe for target 'app' failed
make: *** [app] Error 2
-----------------------------------------------
And then using -> make install <- I get the error...
-------------
cp -vf build/seven-square /usr/bin/
cp: cannot stat 'build/seven-square': No such file or directory
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1

I have no idea how to fix this problem, maybe change my Qt version which is currently Qt 5.6.2 but I noticed the prior commands say qt4 and such.

**Comment by yangh** [comment]
QT4 and QT5 is naturally different, sevensquare doesn't support QT5.

Please install QT4 for compile it.
