### ISSUE TITLE
Invalid FB data len: 8290304 require 8294400

### ISSUE THREAD

**Issue by ahkimkoo** [yangh/sevensquare#23]
1534833297544 Invalid FB data len: 8290304 require 8294400 
1534833297681 Adb exec error... 
1534833297681 Device disconnected 
1534833298065 CAP FB in 512 ms 
1534833298122 Invalid FB data len: 8290304 require 8294400

**Comment by mayel** [comment]
Similar error on a OnePlus 3 device running Android 8.0. Need anything else to debug?

**Comment by yangh** [comment]
Fixed in latest commit 1333e50
