### ISSUE TITLE
weird colors and delay

### ISSUE THREAD

**Issue by arnauldb** [yangh/sevensquare#28]
Hello,

I tried to run sevensquare but I have this result : 

![screenshot_4](https://user-images.githubusercontent.com/13196747/57802893-8ab45180-7746-11e9-8bda-3577dbeaf467.png)

I recorded a video here: https://abordes.ynh.fr/nextcloud/index.php/s/bfaALMDBarSLsDx

Thank you.

**Comment by programmer290399** [comment]
I am facing the same issue , I am using android Oreo 8.1.0

**Comment by yangh** [comment]
Fixed in latest commit 1333e50.

For the delay, there is no way to fix it.
