### ISSUE TITLE
in sevensquare program where buffer is stroring

### ISSUE THREAD

**Issue by ravitejaambati97** [yangh/sevensquare#31]
hello,
please just i want how data is storing in buffer in sevensquare

**Comment by ravitejaambati97** [comment]
can you please anyone please help me to how to identify buffer in sevensquare screencast source code

**Comment by ravitejaambati97** [comment]
@yangh

**Comment by ravitejaambati97** [comment]
hello can anyone please respond

**Comment by yangh** [comment]
Hi Ravi,

Please refer to adbfb.cpp and fbcellitem.cpp. The screen pixel buffer read via adb and rendered into fbcellitem immediately.

BR.
