### ISSUE TITLE
BadDrawable error and white screen

### ISSUE THREAD

**Issue by ReverseBrain** [yangh/sevensquare#4]
Hi, I have a Samsung Galaxy S6 updated to Android 6.0.1. I succesfully installed seven square dependencies and I compiled and installed it. When I run seven-square command from the terminal I receive this error:

`X Error: BadDrawable (invalid Pixmap or Window parameter) 9`
`Major opcode: 62 (X_CopyArea)`
`Resource id:  0x1400013`

And the seven square window is totally white, but if I click on the white screen my phone receive the input.

**Comment by yangh** [comment]
Hi Cricco95

Which Linux distribution are you using? Ubuntu? Fedora? Windows?

Which QT version are you using?

**Comment by Cricco95** [comment]
I am using Kali Linux 2016, Debian 4.4.6 based. I am using QT 4.8.7

**Comment by yangh** [comment]
Hi Circco95

I've test with Nexus 5X which has Android 6.0, Ubuntu 16.04 with QT 4.8.7, and works well. Sorry for that I don't have Kali Linux installed can can't reproduce your issue.
