### ISSUE TITLE
Not working on Nexus 5x Android 6.0.1

### ISSUE THREAD

**Issue by KevinWernerCA** [yangh/sevensquare#5]
Hi, I had everything working on my old Nexus 5.  I just bought a 5x to replace it and seven-square no longer works.  The app just stays in a waiting stage even though I have turned USB debugging on in the developer options on the phone.

Thanks for working on this project!  It has been very helpful.

**Comment by yangh** [comment]
Make sure adb is connected by 'adb shell ls /system/bin/screencap'

**Comment by yangh** [comment]
Fixed in latest commit 1333e50
