### ISSUE TITLE
minigzip executable syntax

### ISSUE THREAD

**Issue by Road-Drum** [yangh/sevensquare#9]
so far I've been able to identify how minigzip is called. however I can't find how the executable is used (syntax for compress/decompress). if it's the same as gzip I can't seem to find where the definition for syntax is.

**Comment by Road-Drum** [comment]
in `adbfb.h`

> // Temp file for compressed fb data
#define GZ_FILE		"/dev/shm/android-fb.gz"

is this location refers to the Android device (source) or Linux device (sink)?

**Comment by yangh** [comment]
It's Linux device. the minizip comes from libz.

A screencap output is copmpressed by gzip on device, transfered to linux via adb shell stdout, saved into the GZ_FILE, and then decompressed by the minizip.

The reason to use the minizip frome libz is that the gzip (built from libz) on a android device use a different compress algorithm (seem it's used in http), which can't be decompressed by gzip on linux device, at less I don't known till now.

best regards

**Comment by yangh** [comment]
please refer to:

int ADBFrameBuffer::screenCap(QByteArray &bytes, int offset)

**Comment by Road-Drum** [comment]
> The reason to use the minizip frome libz is that the gzip (built from libz) on a android device use a different compress algorithm

you mean that this minigzip is not from [Mark Adler's?](https://github.com/madler/zlib/blob/master/test/minigzip.cl)
I've been looking the minigzip from this source. If i have enough capacity maybe I can try to implement it. 
Do you have compiled version of the patched screencap for armv7l? Seems that i am out of resource to clone android git and its tools

**Comment by yangh** [comment]
The minizip comes from https://github.com/android/platform_external_zlib

**Comment by yangh** [comment]
both gzip and minigzip doesn't help much on the sluggish.
